### ISSUE TITLE
Directory with braces does not show contents when expanded

### ISSUE THREAD

**Issue by mcabrams** [preservim/nerdtree#1092] opened 2020-03-16 21:46 UTC
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [x] Operating System: Mac OS 10.15.3
- [x] Vim/Neovim version `:echo v:version`: vim 801
- [x] NERDTree version, found on 1st line in NERDTree quickhelp `?`: 6.7.0
- [x] vimrc settings
    - [x] NERDTree variables
```vim
let NERDTreeIgnore=['doc$', '\.pyc', '\.rbc$', '\~$', '\.DS_Store$', 'tmp', '__pycache__']
let NERDTreeChDirMode=2
let NERDTreeMouseMode=3
let NERDTreeQuitOnOpen=0
let NERDTreeMinimalUI=1
let NERDTreeDirArrows=1
let NERDTreeShowHidden=1
let NERDTreeShowBookmarks=1
```
    - Other NERDTree-dependent Plugins: None

#### Steps to Reproduce the Issue
1. Create a directory called `{foo}` and put a file `bar.txt` inside of it.
2. Open vim (`vim`)
3. In the nerdtree split you'll see `{foo}` folder, if you change focus to that split and put cursor on that, pressing enter to the open the directory will change the arrow to show the directory is open, but not list the `bar.txt` file inside (and will therefore display an apparently empty directory).

#### Current Result (Include screenshots where appropriate.)
![image](https://user-images.githubusercontent.com/1213498/76802362-c370ed00-6794-11ea-94d8-a839bd394f55.png)
![image](https://user-images.githubusercontent.com/1213498/76802390-d08ddc00-6794-11ea-93aa-012fd5289fb0.png)

#### Expected Result

Show contents of directory (i.e. be able to see and select `foo.txt`).

**Comment by mcabrams** [comment] 2020-03-16 21:47
Not sure if this is a regression that took place after #868 - it seems like that PR was meant to solve this issue.

**Comment by PhilRunninger** [comment] 2020-03-16 22:06
@mcabrams, I'm not seeing this behavior. It's possible there's another part of your `.vimrc` file that's responsible. What is causing the L-shaped lines in your first screenshot?

**Comment by mcabrams** [comment] 2020-03-16 22:44
@PhilRunninger That's just the output of the [`tree` command](https://linux.die.net/man/1/tree) in command line to illustrate actual file structure, sorry, should have clarified.

I'll take a look at my .vimrc!

**Comment by mcabrams** [comment] 2020-03-16 22:58
@PhilRunninger FWIW, I just started vim with `vim -u .vimrc` where vimrc looked like the following:

```vim
call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree'
call plug#end()
```

and I had the same issue.

**Comment by mcabrams** [comment] 2020-03-16 23:28
An additional note, if instead of pressing `o` I press `t` to open in a new tab, the contents show appropriately in the new tab (this is regardless of whether I'm using current vimrc or minimal vimrc).

**Comment by PhilRunninger** [comment] 2020-03-17 00:17
I made a similar minimalist setup. I have a `~/.vim/vimrc` with only
```vim
packadd nerdtree
```
in it, and nerdtree is located in `~/.vim/pack/bundle/opt/nerdtree`. There is nothing else in my `~/.vim` folder. Even when using the `vim -u broken_vimrc` command, vim will still read your `~/.vim` folder. If there are other vim scripts in the tree (such as in the `~/.vim/ftplugin`, `~/.vim/after`, `~/.vim/plugin`, or `~/.vim/syntax` folders), they will be sourced and may affect what's happening.

With my minimalist setup, I still cannot reproduce the error, and `t` works properly as you describe.

**Comment by mcabrams** [comment] 2020-03-17 18:35
@PhilRunninger So odd, I have the exact same setup, yet I still have the same issue:
![image](https://user-images.githubusercontent.com/1213498/76889414-c88c7580-6842-11ea-8159-397375edcc51.png)

I'm assuming this must have something to do with vim version or something else?

**Comment by mcabrams** [comment] 2020-03-17 18:36
FWIW:

```
➤ vim --version                                                                                                       11:35:08
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  3 2020 12:05:00)
macOS version
Included patches: 1-319
Compiled by travis@Traviss-Mac.local
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
+balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +fullscreen        +num64             +textobjects
+browse            -gettext           +odbeditor         +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     +perl/dyn          +toolbar
+cindent           +job               +persistent_undo   +transparency
+clientserver      +jumplist          +popupwin          +user_commands
+clipboard         +keymap            +postscript        +vartabs
+cmdline_compl     +lambda            +printer           +vertsplit
+cmdline_hist      +langmap           +profile           +virtualedit
+cmdline_info      +libcall           +python/dyn        +visual
+comments          +linebreak         +python3/dyn       +visualextra
+conceal           +lispindent        +quickfix          +viminfo
+cryptv            +listcmds          +reltime           +vreplace
+cscope            +localmap          +rightleft         +wildignore
+cursorbind        +lua/dyn           +ruby/dyn          +wildmenu
+cursorshape       +menu              +scrollbind        +windows
+dialog_con_gui    +mksession         +signs             +writebackup
+diff              +modify_fname      +smartindent       -X11
+digraphs          +mouse             -sound             -xfontset
+dnd               +mouseshape        +spell             +xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        -mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary
-farsi             -mouse_sysmouse    -tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework AppKit   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE
```

**Comment by PhilRunninger** [comment] 2020-04-21 02:29
I know this is a long shot, because you would have already noticed it. Do you, by chance, have 
```vim
let NERDTreeShowFiles = 0
```
in your **vimrc**? The `F` keystroke in NERDTree will toggle the display of files on and off. Does reveal your missing file?

**Comment by PhilRunninger** [comment] 2020-05-19 02:55
I'm thinking it has something to do with the way the `globpath()` function and/or your OS shell interprets the braces. I'm using the bash shell. Let's see if these questions help.

1. What shell are you using? `echo $SHELL`
1. What value does your Vim `shell` setting have? `:set shell?`
1. What does this command return? You may need to use the full path.
```vim
echo globpath('source-dirs/{{cookiecutter.name}}', '*', 0, 1, 0)
```

**Comment by DaniloZZZ** [comment] 2020-05-20 07:24
Yep, seems like it is the issue, I use fish shell


```
~ » echo $SHELL  
/usr/bin/fish

~ » echo globpath('{foo}', '*', 0, 1, 0)      

fish: Unknown command: '{foo},'
in command substitution
fish: Unknown error while evaluating command substitution
```
in vim:
```
  shell=/usr/bin/fish
```
`:set shell=/bin/bash` resolves the isssue

**Comment by PhilRunninger** [comment] 2020-05-20 13:06
Just to be clear, the `:echo globpath...` statement should be run inside of Vim. Make sure you use the actual file path of the folder with braces in it's name. Try it again, and report back what it does.

**Comment by DaniloZZZ** [comment] 2020-05-21 00:47
Running `:echo globpath` in parend of `{{cookiecutter.name}}` dir returns `[]`. Running `:set shell=/bin/bash` and then globbing returns list of files

Maybe there is some way to escape those braces? Or I should just set my vim shell to bash?

**Comment by PhilRunninger** [comment] 2020-05-21 01:57
If `set shell=/bin/bash` works and doesn't break anything else, I see no reason to not do that. I wonder if this is a Vim bug. @mcabrams, what shell are you running vim in? I wonder if there's a similar issue on the Mac.

**Comment by PhilRunninger** [comment] 2020-05-21 02:40
Escaping, as shown below, does work, but I think it should work consistently between shells. I will open an issue in the Vim project. I also confirmed this can be recreated in the fish shell on a Mac. 
```vim
echo globpath(escape('source-dirs/{{cookiecutter.name}}','{}'), '*', 0, 1, 0)
```

**Comment by PhilRunninger** [comment] 2020-05-21 06:36
On second thought, this is easily fixed in NERDTree, and calling this a bug in Vim will likely get shot down. The Vim function `fnameescape()` will properly escape the filename, but NERDTree also has its own way of escaping filenames. Don't ask me why; maybe it was there before Vim built it in.

Anyway, checkout the branch 1092, and give it a shot without your `set shell=/bin/fish` statement.

**Comment by DaniloZZZ** [comment] 2020-05-22 23:18
Checked out branch 1092, dir expansion works fine, thank you!

1. **Code injection**
It is surprising that listing files has anything to do with shell. Does it mean that eventually name of directory is passed to shell? If yes, the escaping should be done for every shell, otherwise I can do nasty things just by having directory `danger_$(rm -rf /)_dir` or whatever is analog in other shells. I suppose the escaping should be done on vim level.

2. **Error handling**
Why does it return empty list instead of propagating the error from shell?

**Comment by PhilRunninger** [comment] 2020-05-25 16:19
1. NERDTree is escaping the folder name before calling `globpath()` for all shells, and I don't think it actually runs in a shell. The new change here is that braces are escaped.
2. My guess is that since the command doesn't run in the shell, there is no shell error to return. The empty list probably indicates there is no such path with unescaped braces.

**Closed** 2020-05-26 04:15 UTC
Labels: awaiting feedback, bug
