### ISSUE TITLE
Error detected while processing WinEnter Autocommands for "*"..function <SNR>38_HandleOnlyWindow[13]..<SNR>38_CloseWindow:

### ISSUE THREAD

**Issue by lijh8** [preservim/nerdtree#1403] opened 2024-02-01 14:36 UTC
#### Self-Diagnosis
Before creating an issue, take some time to search these resources for an answer. It's possible that someone else has already seen and solved your issue.
- [old NERDTree issues](https://github.com/preservim/nerdtree/issues?q=is%3Aissue)
- NERDTree documentation - `:h NERDTree`
- [NERDTree Wiki](https://github.com/preservim/nerdtree/wiki)
- Other resources: <https://stackoverflow.com>, <https://vi.stackexchange.com>, etc.

#### Environment
- Operating System: macOS 12.7.3 (21H1015)
- Vim/Neovim version `:version`: VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Oct 27 2023 01:00:56)
- NERDTree version, found on first line of quickhelp `?`: NERDTree (7.1.1) quickhelp~
- Are you using any of these NERDTree-dependent plugins?  
    - [ ] [Xuyuanp/nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin)
    - [ ] [ryanoasis/vim-devicons](https://github.com/ryanoasis/vim-devicons)
    - [ ] [tiagofumo/vim-nerdtree-syntax-highlight](https://github.com/tiagofumo/vim-nerdtree-syntax-highlight)
    - [ ] [scrooloose/nerdtree-project-plugin](https://github.com/scrooloose/nerdtree-project-plugin)
    - [ ] [PhilRunninger/nerdtree-buffer-ops](https://github.com/PhilRunninger/nerdtree-buffer-ops)
    - [ ] [PhilRunninger/nerdtree-visual-selection](https://github.com/PhilRunninger/nerdtree-visual-selection)
    - [ ] [jistr/vim-nerdtree-tabs](https://github.com/jistr/vim-nerdtree-tabs)
    - [x] Others (specify): github.com/preservim/tagbar
- Provide a minimal **.vimrc** file that will reproduce the issue.
```vim


set expandtab
set hlsearch
set nowrapscan
set shiftwidth=4
set smartindent
set tabstop=4
syntax off

" NERDTree
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif
autocmd BufEnter * if winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif
autocmd VimEnter * NERDTree
let g:NERDTreeNodeDelimiter = "\u00a0"
nnoremap <leader>n :NERDTreeFocus<CR> " \ - n
nnoremap <C-n> :NERDTree<CR>          " Ctrl - n
nnoremap <C-t> :NERDTreeToggle<CR>    " Ctrl - t
nnoremap <C-f> :NERDTreeFind<CR>

" tagbar
filetype on            " Tagbar: Filetype detection is turned off, skipping plugin
let g:tagbar_sort = 0  " order of position
nmap <F8> :TagbarToggle<CR>

```

#### Steps to Reproduce the Issue
1. 

Hi, i'm using vim with nerdtree and tagbar. 
with both nerdtree and tagbar toggled on, when i quit editing my last c++ source file, there's this error:

```
Error detected while processing WinEnter Autocommands for "*"..function <SNR>38_HandleOnlyWindow[13]..<SNR>38_CloseWindow:
line   21:
E1312: Not allowed to change the window layout in this autocmd

```

#### Current Behavior (Include screenshots where appropriate.)

![Screen Shot 2024-02-01 at 22 33 58](https://github.com/preservim/nerdtree/assets/9011764/61a793f5-9c06-4bd7-8c15-687f83978880)
![Screen Shot 2024-02-01 at 22 34 04](https://github.com/preservim/nerdtree/assets/9011764/3f0d51f0-5d21-4441-981f-7a19fdc26bb5)

#### Expected Result

Do not know whether it's related to nerdtree, tagbar, or vim.

**Comment by rzvxa** [comment] 2024-02-05 14:03
Hi, Sorry for the late response.
The origin of this error(`HandleOnlyWindow`) is in the `tagbar` plugin, You may have to create an issue on the [tagbar](https://github.com/preservim/tagbar/issues) project to get some help with it.

I suggest you get rid of everything that isn't related to the `tagbar` and try again. If it is caused by something external it would be gone otherwise you will be sure that it is from the `tagbar` plugin. You can also remove other configurations one by one until either the error is gone or you only have a few lines for importing the `tagbar` plugin and nothing else(including any configuration for the `tagbar` itself).

Since this issue isn't related to the `NERDTree` plugin, I'm going to close it. Feel free to create a new issue if you encounter any problems with the NERDTree in the future.

**Closed by rzvxa** 2024-02-05 14:03 UTC
Labels: bug
