### ISSUE TITLE
Not able to expand dirs and files starting with ~

### ISSUE THREAD

**Issue by Arteneko** [preservim/nerdtree#1351] opened 2023-02-24 13:30 UTC
On neovim, with most recent plugin commit, I cannot expand directories starting with the character `~`, and file names can be opened but neovim throws the following error in console first.

```
E79: Cannot expand wildcards
```

This can be reproduced by the following structure.

```
.
├── ~not-found
├── ~test-dir
│   └── not-found
├── test-dir
│   └── found
└── test-file.md
```

Neovim version:

```
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/q5d6krrh9abkrsbs20k4g0x3k646cgfx-neovim-unwrapped-0.8.1/share/nvim
"
```

**Comment by rzvxa** [comment] 2023-08-21 20:27
@Arteneko What is your OS and filesystem? I've tried this with both Windows and Linux but only with NTFS filesystem (WSL) and this never happened, I'm not sure of any limitations like this exists on ext4 either.

**Comment by rzvxa** [comment] 2023-10-26 00:13
I'm going to close this issue since It's not reproducible and the author of the issue hasn't replied to the request for more information in a while.
Feel free to reopen this issue if you are still experiencing the same issue.

**Closed by rzvxa** 2023-10-26 00:13 UTC
