### ISSUE TITLE
Minibufexpl and NerdTree conflict

### ISSUE THREAD

**Issue by yapbreak** [preservim/nerdtree#1065] opened 2019-12-02 09:56 UTC
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [x] Operating System: GNU/Linux
- [x] Vim/Neovim version `:echo v:version`: Vim 801
- [x] NERDTree version, found on 1st line in NERDTree quickhelp `?`: 6.2.1
- [x] vimrc settings (my full configuration is available at https://gitlab.yapbreak.fr/configuration/vim.git)
    - [x] NERDTree variables
    ```vim
    autocmd StdinReadPre * let s:std_in=1
    autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
    autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif
    map <F2> :NERDTreeToggle<CR>
    map " :NERDTreeFind<CR>
    autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
    let NERDTreeMapActivateNode='o'
    let NERDTreeMapOpenInTab='é'
    let NERDTreeMapOpenInTabSilent='É'
    let NERDTreeMapOpenSplit='h'
    let NERDTreeMapOpenVSplit='v'
    let NERDTreeMapOpenRecursively='O'
    let NERDTreeMapCloseDir='x'
    let NERDTreeMapCloseChildren='X'
    let NERDTreeMapOpenExpl='e'
    let NERDTreeMapDeleteBookmark='D'
    let NERDTreeMapJumpRoot='P'
    let NERDTreeMapJumpParent='p'
    let NERDTreeMapJumpFirstChild='B'
    let NERDTreeMapJumpLastChild='b'
    let NERDTreeMapJumpNextSibling='<C-T>'
    let NERDTreeMapJumpPrevSibling='<C-S>'
    let NERDTreeMapChangeRoot='C'
    let NERDTreeMapUpdir='u'
    let NERDTreeMapUpdirKeepOpen='U'
    let NERDTreeMapRefresh='r'
    let NERDTreeMapRefreshRoot='R'
    let NERDTreeMapMenu='m'
    let NERDTreeMapChdir='cd'
    let NERDTreeMapCWD='CD'
    let NERDTreeMapToggleHidden='<C-h>'
    let NERDTreeMapToggleFilters='f'
    let NERDTreeMapToggleFiles='F'
    let NERDTreeMapToggleBookmarks='a'
    let NERDTreeMapQuit='q'
    let NERDTreeMapToggleZoom='A'
    let NERDTreeMapHelp='?'
    let NERDTreeChDirMode=2
    let NERDTreeIgnore=['\.git$', '\.svn$', '\.o$[[file]]', '\.d$[[dir]]', '__pycache__$[[dir]]']
    let NERDTreeRespectWildIgnore=1
    let NERDTreeBookmarksFile='$HOME/.vim/bookmarks'
    let NERDTreeMouseMode=2
    let NERDTreeShowBookmarks=1
    let g:NERDTreeShowIgnoredStatus = 1
    ```
    - Other NERDTree-dependent Plugins
        - [ ] jistr/vim-nerdtree-tabs
        - [ ] ryanoasis/vim-devicons
        - [ ] tiagofumo/vim-nerdtree-syntax-highlight
        - [x] Xuyuanp/nerdtree-git-plugin
        - [ ] Others (specify): 
    - [ ] I've verified the issue occurs with only NERDTree installed. (This is not relevant in my case)

#### Steps to Reproduce the Issue
1. Open multiple files with Vim
2. Open NERDTree AND Minibufexpl
3. Switch from one file to another through Minibufexpl

#### Current Result (Include screenshots where appropriate.)

When switching from existing file to another existing file through Minibufexpl, NerdTree pane will go up to parent directory view and change CWD accordingly.

#### Expected Result

When using NERDTree 6.0.1, issue goes away. It is introduce by commit 6318406.
I expect that NERDTree stay in the same view.

(As a side note, thank for your plugin that I use everyday!)

**Comment by PhilRunninger** [comment] 2020-01-29 16:30
I cannot reproduce this behavior. Please provide a minimal `.vimrc` that demonstrates the issue.

**Comment by yapbreak** [comment] 2020-01-29 21:12
Hi,
I just reproduce issue in a -- kind of -- minimal environment:
On a brand new user, I run the following commands to install plugins:

```bash
mkdir -p .vim/pack/test/start && cd .vim/pack/test/start
git clone https://github.com/scrooloose/nerdtree
git clone https://github.com/fholgado/minibufexpl.vim
```
And I use the following .vimrc:

```
set nocompatible
set mouse=a
noremap <Leader>bd <ESC>:MBEbd<CR>

autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif

map <F2> :NERDTreeToggle<CR>
map " :NERDTreeFind<CR>

autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

let NERDTreeChDirMode=2
let NERDTreeIgnore=['\.git$', '\.svn$', '\.o$[[file]]', '\.d$[[dir]]', '__pycache__$[[dir]]']
let NERDTreeRespectWildIgnore=1
let NERDTreeBookmarksFile='$HOME/.vim/bookmarks'
let NERDTreeMouseMode=2
let NERDTreeShowBookmarks=1

let g:NERDTreeShowIgnoredStatus = 1
```

Then, I go in an empty dir, create two files (say test1 and test2) with touch.
I start vim (without any argument). With my configuration, NERDTree is open automatically. Through NERDTree, I open test1 and test2 (with keyboard or mouse, it does not matter).
With `test1` open in main buffer, if I want to open `test2` through MinibufExplorer (either double click or simple click/keyboard move to it and press <CR>), I get the following error message:

```
NERDTree: CWD is now: /
Error detected while processing function <SNR>16_MBESelectBuffer[10]..<SNR>16_GetSelectedBuf
fer[17]..<SNR>33_findAndRevealPath[45]..166:
line    4:
E605: Exception not caught: NERDTree.InvalidArgumentsError: /home should be under /
```

Note: to reproduce, I use the following versions:
  - Vim 802
  - NERDTree version 6.5.0 (in fact, top of master branch at commit 8c48845d11adc4c9b07fc727725ed68be5d3177f, tagged 6.5.0)
  - MinibufExplorer version 6.5.2 (in fact, top of master branch at commit ad72976ca3df4585d49aa296799f14f3b34cf953, tagged 6.5.2)

**Comment by PhilRunninger** [comment] 2020-01-30 23:04
@yapbreak Thanks for the additional information. (As it turns out, it wasn't necessary, if I had taken a closer look at your original text of the issue.) I found the cause, and there are two possible solutions, neither one involving NERDTree.

The NERDTree function throwing the error (`findAndRevealPath`) is called only by the `:NERDTreeFind` command, so I turned on the Vim logging,

```vim
set verbosefile=log
set verbose=15
```

and looked through the log file for "NERDTreeFind". I found it being called here:
```
line 17:   normal ""yi[
Executing:   normal ""yi[
line 17: NERDTreeFind
Executing: NERDTreeFind
line 17: call s:findAndRevealPath('')
Executing: call s:findAndRevealPath('')
calling <SNR>31_findAndRevealPath('')
```

"That's a rather odd place to be calling NERDTreeFind," I thought. That's when I noticed your mapping:
```vim
map " :NERDTreeFind<CR>
```

So here are the two solutions:
1. Raise an issue in [minibufexpl](https://github.com/fholgado/minibufexpl.vim) to change [line 2161](https://github.com/fholgado/minibufexpl.vim/blob/master/plugin/minibufexpl.vim#L2161) to:
   ```vim
   normal! ""yi[
   ```
   so that it uses the original definition of `"` and yanks the buffer name into the unnamed register, instead of invoking your mapping.
1. Map a different key in your `.vimrc`. (*I recommend* `nnoremap` *to avoid recursive mapping*):
    ```vim
    nnoremap <S-F2> :NERDTreeFind<CR>
    ```

I think the first solution is likely to go nowhere, as that project has been dormant for almost 7 years, but [this fork](https://github.com/qiqiboy/minibufexpl.vim) seems to be new within the last month.

Since there is nothing to do in NERDTree to fix this, I'm going to close this issue. Let me know how this works out for you.

**Closed by PhilRunninger** 2020-01-30 23:04 UTC
Labels: Needs More Info, bug

**Comment by PhilRunninger** [comment] 2020-01-30 23:10
There are other forks that may be active. You can see them [here](https://github.com/fholgado/minibufexpl.vim/network). I don't know which, if any, are official now, but you can try raising issues in them to find out. [l-qing's fork](https://github.com/l-qing/minibufexpl.vim) looks like it might be promising too.

**Comment by yapbreak** [comment] 2020-02-02 14:27
Thank you for your complete analysis!
If I patch my copy of minipufexpl with your patch, everything seems to work well!
I will investigate on minibufexpl fork now and found a suitable one!
