### ISSUE TITLE
<C-O> doesn't work in NERDTree

### ISSUE THREAD

**Issue by qstrahl** [preservim/nerdtree#250] opened 2013-04-22 15:19 UTC
# Procedure
1. I am in file `/var/www/example`
2. I jump to directory `/var/www/derpherper/`
3. I hit `<C-O>` to go back to `/var/www/example`
# Erroneous Result

The cursor is placed on the last line in NERDTree
# Expected Result

Vim jumps back to `/var/www/example`

**Comment by juanibiapina** [comment] 2017-09-26 15:04
There are many bugs involving ctrl+o and nerd tree, it becames unusable if you're using `:e .`

**Comment by lifecrisis** [comment] 2017-09-26 15:22
I'm unable to replicate this problem right now.  If either of you could provide more specific examples, I'd be willing to try and confirm.

**Comment by juanibiapina** [comment] 2017-09-26 15:33
Steps:

- clear jump list
- create two files called `1` and `2`
- `:e 1`
- `:e 2`
- `:e .` (with hijack, opens nerd tree)
- ctrl+o (goes to end of nerd tree, annoying but fine)
- ctrl+o (goes to file 1, wrong, end of jumps)
- ctrl+i (goes to file 2, correct)

After that you can play around with ctrl+o and ctrl+i and even though the jump list seems to be correct, it jumps to weird places.

I just added this line from the documentation which seems to improve the behavior for my example tests:
```
let NERDTreeCreatePrefix='silent keepalt keepjumps'
```

Although I still get jumps back to nerd tree and inside of it. I'm not sure I want this behavior. I'll live with my fix for a while and figure out later if I want nerdtree to mess with the jumplist at all.

**Comment by lifecrisis** [comment] 2017-09-26 18:28
Very good work, @juanibiapina.  This bug is confirmed.

**Comment by lifecrisis** [comment] 2017-09-26 19:48
I discovered another instance of this problem just now:

1. Position the cursor on a directory node that is no the root.
2. Press `P`.
3. Press `R` to refresh the tree.
4. Press `<C-O>` and notice that the cursor jumps to the end of the NERDTree window.

There is clearly a problem with the way that the NERDTree does not preserve jumps when printing the tree to the tree window.

**Comment by juanibiapina** [comment] 2017-09-26 20:21
The worst case is when ctrl+o does not work at all, even though jumplist is full of stuff. I can't reproduce it in isolation, although it happens to me everyday.

**Comment by juanibiapina** [comment] 2017-09-28 14:03
I'm working on a different project now because nerdtree is too bloated and I don't use the drawer and per-tab windows anyway, but part of the fix for this is easy enough so you can port from here: https://github.com/juanibiapina/vim-lighttree/commit/2521fe4a4b01b8c830403f8654ca9b5925657ffe

**Comment by lifecrisis** [comment] 2017-09-28 16:53
Thanks, @juanibiapina!  I had played with a similar fix, myself.

**Comment by PhilRunninger** [comment] 2020-06-26 20:12
There is no single way to define what `<C-O>` and `<C-I>` do in the context of NERDTree. Should it jump between the selected roots of NERDTree? Or should it jump between selected files? What constitutes a file selection? What happens when a folder is expanded; now `<C-O>` could jump back to the wrong location.

For all these reasons, and more, I'm going to close this issue. If anyone proposes a viable specification for this functionality, I'll entertain it.

**Closed by PhilRunninger** 2020-06-26 20:12 UTC
Labels: bug
