### ISSUE TITLE
Double curly braces in directory name break expansion

### ISSUE THREAD

**Issue by DaniloZZZ** [preservim/nerdtree#1127] opened 2020-05-19 00:19 UTC
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [n/a ] I have reviewed the NERDTree documentation. `:h NERDTree`
- [n/a ] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [x] Operating System: Linux archlinux 5.6.13-arch1-1 #1 SMP PREEMPT Thu, 14 May 2020 06:52:53 +0000 x86_64 GNU/Linux
- [x] NVIM v0.4.3
- [x] NERDTree version: 6.7.11 
- [x] NERDTree variables
```vim
$ cat ~/.vimrc|grep -i nerd
Plug 'preservim/nerdtree'
map <C-n> :NERDTreeToggle<CR>
let NERDTreeShowHidden=1

```
- [x] I've verified the issue occurs with only NERDTree installed.

#### Steps to Reproduce the Issue
1. Create a directory with double curly braces in name.
2. Try to expand it in tree view

#### Current Result (Include screenshots where appropriate.)

Note the triangles near the dir, it is marked as expanded. 
```
  ▾ source-dirs/
    ▸ .git/
    ▾ {{cookiecutter.name}}/
      cookiecutter.json
  ▾ source-files/
    ▸ .git/
    ▾ {{cookiecutter.name}}/
      cookiecutter.json

```

Dirs are not empty:
```
» tree -L 2 source-dirs/
source-dirs/
├── cookiecutter.json
└── {{cookiecutter.name}}
    ├── Makefile
    ├── README.md
    ├── back
    ├── front
    ├── js_requirements.txt
    ├── libvis-mod.conf
    └── py_requirements.txt
```
#### Expected Result
list of files in dirs

**Comment by DaniloZZZ** [comment] 2020-05-19 00:30
Ok, with braces instead of curly brackets I found this issue #1092, so this one may be a duplicate

**Comment by PhilRunninger** [comment] 2020-05-19 02:57
This **is** a duplicate of #1092 . I'm closing this one. Please respond to the comments in that issue.

**Closed by PhilRunninger** 2020-05-19 02:57 UTC
Labels: bug, duplicate
