### ISSUE TITLE
NerdtreeToggle will sometimes losts its width.

### ISSUE THREAD

**Issue by jinleileiking** [preservim/nerdtree#142] opened 2012-02-22 02:53 UTC
Sometime,     Use NerdtreeToggle, The nerdtree window will be maximized.

**Comment by PhilRunninger** [comment] 2018-03-15 00:51
@jinleileiking , I've been going through the backlog of issues. I cannot reproduce this issue. Can you provide more information about this, or close the issue?

**Closed as completed** 2018-03-15 05:23 UTC

**Comment by leighmcculloch** [comment] 2020-07-13 06:18
There's not a ton of information on this issue so I can't be sure, but I think I have experienced this issue. I've opened a new issue that focuses specifically on the situation I'm experiencing: #1152.
